on: push
name: ⚙️ Build
jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: 🔨 Build
        working-directory: ./src/fronend
        run: |
          npm install
          npm run build
  backend:
    name: Backend
    runs-on: windows-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        run: dotnet restore ./src/backend
      - name: 🛠️ Build
        run: dotnet build --configuration Release ./src/backend
      - name: 🧪 Test
        run: dotnet test --configuration Release ./src/backend
