name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - "src/frontend/**"

jobs:
  frontend:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: ./src/frontend/yarn.lock

      - name: 📦 Install packages
        working-directory: ./src/frontend
        run: yarn install

      - name: 🧪 Test
        working-directory: ./src/frontend
        run: yarn test

      - name: 🛠️ Build
        working-directory: ./src/frontend
        run: yarn build

      - name: 🚀 Deploy
        uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521 # 4.2.0
        with:
          server: ftp.swharden.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/frontend/build/
          server-dir: /qrss/plus/
          log-level: minimal
